version: '3.4'

services:
  anonymizer:
    build:
      context: .
    depends_on:
      - db-mysql
#      - db-postgres
    volumes:
      - ./:/opt/
    env_file:
      - local.env
    networks:
      - db-net


  db-mysql:
    image: mysql:8.0
    container_name: mysql-dump-db
    restart: always
    command: >
      sh -c "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --port=3306 && 
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --port=3306"
#    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--port=3306']
#    env_file:
#      - local.env
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: tmp_db
      MYSQL_PORT: 3306     
      MYSQL_USER: dumper
      MYSQL_PASSWORD: dumper
    networks:
      - db-net
    ports:
      - 0.0.0.0:3306:3306


#  db-postgres:
#    image: postgres:11.1
#    container_name: postgres-dump-db
#    env_file:
#      - local.env
#    networks:
#      - db-net
#    ports:
#      - 5432
  
networks:
  db-net:
    driver: bridge