version: '3.8'

services:
  anonymizer:
    container_name: anonymizer
    build:
      context: .
    depends_on:
      db-mysql:
        condition: service_healthy
      db-mariadb:
        condition: service_healthy
      db-postgres:
        condition: service_healthy
    volumes:
      - ./:/opt/
    env_file:
      - default.env
      - $DB_FILE
      - $PROJECT_FILE
    networks:
      - db-net

  db-mysql:
    image: mysql:8.0
    container_name: mysql-dump-db
    restart: unless-stopped
    command: [ 'mysqld', '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--port=3306' ]
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: ignore
    healthcheck:
      test: [ "CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -pmysql" ]
      interval: 5s
      timeout: 20s
      retries: 30
    networks:
      - db-net

  db-mariadb:
    image: mariadb:10.6
    container_name: mariadb-dump-db
    restart: unless-stopped
    command: [ 'mysqld', '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--port=3309' ]
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: ignore
    healthcheck:
      test: [ "CMD-SHELL", "exit | mysql -h localhost -P 3309 -u root -pmariadb" ]
      interval: 5s
      timeout: 20s
      retries: 30
    networks:
      - db-net

  db-postgres:
    image: postgres:14
    container_name: postgres-dump-db
    environment:
      POSTGRES_PASSWORD: postgres
      MYSQL_DATABASE: ignore
    healthcheck:
      test: [ "CMD-SHELL", "exit | env PGPASSWORD=postgres && psql -d postgres -Upostgres" ]
      interval: 5s
      timeout: 20s
      retries: 30
    networks:
      - db-net

networks:
  db-net:
    driver: bridge